num1 = input('Give me first number: ')
print(f"{num1}")
num2 = input('Give me second number: ')
print(f"{num2}")
addition = int(num1) + int(num2)
print(f"{num1} + {num2} = {addition}")

subtraction = int(num1) - int(num2)
print(f"{num1} - {num2} = {subtraction}")
multiplication = int(num1) * int(num2)
print(f"{num1} * {num2} = {multiplication}")
